### ISSUE TITLE
Big with plugin ProtocolLib

### ISSUE THREAD

**Issue by ghost** [Inventory-Tweaks/inventory-tweaks#125]
Hi!

Everything will start something like this - first server will occasionally freezes for a few seconds, during which time chat will not work, entity just freeze and shit happens. After can't take any drop, ejected by the open chest (because it becomes visual for client), and then start other obscurantism. Moreover, all different.
And do not say that such ProtocolLib oh shit - it saves players from network errors, such disconnect.overflow, treats many crashes associated with packages and modes. Simply, it's a crap InvTweaks.

I hope you will understand me correctly, because I don't speak English so well, goodbye!

**Comment by Kobata** [comment]
I cannot support bukkit plugins messing with things, _especially_ bukkit plugins that interfere at such a low level.

Any issues they have are their fault, because I am either telling Minecraft 'a click happened here' and letting it take care of everything else, or (with forge/MCPC+ and a copy of InvTweaks installed on the server) a custom packet that should not be processed by anything else.
