### ISSUE TITLE
Sorting drops items on ground and fail to sort

### ISSUE THREAD

**Issue by TheIceBadger** [Inventory-Tweaks/inventory-tweaks#155]
It seems that some items cause the sorting to fail and then those items are thrown onto the ground.
It seems to happen mostly with enchanted tools, the Diamond Shovel always seems to be dropped, though other items (enchanted only?) also seem to be thrown out when sorting and the sort never applies. 
This happens when sorting inventory and when sorting chests.
Using the latest version of inventory tweaks (1.57-116) and forge for MC 1.7.2

Hope this can be fixed!

**Comment by Kobata** [comment]
Most reports of these are from people playing on servers, where the issue is cased by issues in how the server (or mods/plugins installed on the server) handle items.

In general, these issues _cannot_ be solved on the client-side, although having the server operator install a copy of this mod on the server will enable a hacky bypass of the code that tends to be an issue.

**Comment by Wolterhon** [comment]
Ugh, maybe you could make the things happen not so fast and make server think that I just used my mouse?
