### ISSUE TITLE
randomly moving items between chest and inventory

### ISSUE THREAD

**Issue by MiK3gamer** [Inventory-Tweaks/inventory-tweaks#17]
hi.
this i already happened in minecraft 1.2.5 in the modpack for the Feed The Beast map, and the bug still exists today.
Inventory tweaks sometimes moves an item/stack from my inventory to a chest, or from a chest to my inventory. that happens while just opening the chest.
and i am not the only on, this also happened to the (pretty famous) youtuber "direwolf20", hope you know who he is ;)

i got two video proofs (during a Let's Play series) where you can see it. 
my video (german): http://youtu.be/gjXgYWo5s34
between 8:10 and 8:20. 
look at the diamond block that randomly appears in my hotbar when opening the chest

direwolf20: http://www.youtube.com/watch?v=hM9P5PDS6VA&feature=share&list=PLaiPn4ewcbkH4f-aZfmdUur9fgXhIJyxH
between 7:00 and 7:15
look at his Minium Stone. he has it in his inventory while crafting. when he opens the chest, it instantly appears in his chest.

it is also really dangerous in some situations. i can't use inv tweaks on my server anymore, because it blew up my nuclear reactor like 3 times.
how could inv tweaks blow up a reactor?
it simply moved a component heat vent fromthe reactor to my inventory. the reactor overheated because of that, and boom!

hope that'll be fixed soon :(

**Comment by Kobata** [comment]
Does this happen in MC1.5? I fixed a cause of these things quite a while ago: 093fb400ed686617a152a45f0c63fe5998f1b691. See also, issue #2

That particular one, and what I think you're reporting here, is the shortcuts misfire when you are holding down forward or backward [w/s on US keyboards] while opening a chest/other GUI and the item that is under where your cursor appears is moved.

**Comment by Kobata** [comment]
Oh, I should mention that my modified build for MC1.4.7 also contains that particular fix: http://www.mediafire.com/download.php?isg82e8ut0to1z1

**Comment by MiK3gamer** [comment]
thank, i will try it as soon as possible.
i have to admit that i didnt try the newest version yet.
i am playing the direwolf20 modpack (from the Feed the Beast launcher), which still uses inv tweaks 1.50 (i guess that's the latest release by jimeowan). maybe i should have mentioned that.
and to be honest, i didnt expect it to be already fixed in the newest version, cause it hasnt been fixed for so long.

well, as i said, i will test the fixed 1.4.7 release soon, but i can't test if that bug is still existing. because it happens randomly, and not for a particular reason. so i dont know how to purposely let it happen.

**Comment by Kobata** [comment]
Looking at both your videos this should be fixed [in both cases you're walking towards a chest while opening it], so closing as duplicate for now.

It's not actually 'random', few things really are, but it certainly seems that way until you know the actual reason.

When you open a chest you have the right mouse button down, Inventory Tweaks isn't checking until a GUI is opened so it thinks you just pressed it when the UI opens before you release the button. If you have a key down that triggers a shortcut -- in this case, forward/backward movement keys + rightclick is a shortcut -- it tries to run that shortcut. When a GUI is initially opened the mouse cursor is in the middle of the screen, which happens to correspond to a slot in your inventory or a chest depending on the size of the chest's inventory.

The fix was simply to ignore the mouse being down until the first time it is released after a GUI opens.
