### ISSUE TITLE
Items being thrown on the ground

### ISSUE THREAD

**Issue by Xyphos** [Inventory-Tweaks/inventory-tweaks#182]
Whenever I press the sort key ("R")
my renamed enchanted diamond garments does not get equipped
my renamed enchanted bow or enchanted diamond sword disappears
opening inventory does not show the missing item
closing inventory throws the missing item on to the ground

I'm a bit paranoid when using your mod around other players so I'm forced to teleport to my home every time I want to sort because my equipment is considered to be "expensive" on the server I play.

**Comment by Kobata** [comment]
Some items/server plugins can interfere with the sorting process's attempts to move items _on the server_, this leaves items 'stuck' to your currently picked-up item which can get a bit glitchy if it happens when an inventory screen is not open.

This is not fixable on the client-side only install, and is the reason the mod supports installation on servers.
