### ISSUE TITLE
Block picking up configured items

### ISSUE THREAD

**Issue by ChrisLane** [Inventory-Tweaks/inventory-tweaks#192]
Currently the mod is only concerned with sorting items and moving items in inventories however since it's called Inventory Tweaks I think this is a valid suggestion.

I have checked the wiki and issues and haven't found anything similar to this yet.

Some people often find themselves dumping materials from their inventory that they do not want for example cobble while mining.
It would be good to be able to block certain items going into certain slots, this way people could select in the config to have for example cobble blocked for all but two slots.
Alternatively players could block an item for all slots.

This could be done through blacklisting items for slots or it might make more sense to be able to set a limit for the number of an item in the inventory so that they can be configured for sorting the normal way.

It's late and so I might not have made this very clear but basically I would like a way to block for example all spider eyes being picked up and allow for 1 stack only of cobble to be picked up that I can set the location of in my hotbar.

**Comment by Kobata** [comment]
Inventory Tweaks doesn't have the control necessary to do anything along these lines without massive lag (checking the inventory constantly because it's a primarily client mod and pickup notifications only work correctly on the server) and throwing items on the ground (because, as a client mod, it can't actually _stop_ you from picking anything up).
