### ISSUE TITLE
FML vs. LiteLoader

### ISSUE THREAD

**Issue by EasyMFnE** [Inventory-Tweaks/inventory-tweaks#196]
I plan on looking into the code myself as I seek an answer, but I thought it would also be a good idea to ask my question here.  To what extent does this mod depend on functionality from Forge/FML?  I see that it now uses MCP, so I was looking into the possibility of a conversion to work with LiteLoader.

**Comment by Kobata** [comment]
Pretty much all the code that figures out what GUIs to use and where things are located (that is, all the stuff in the container part of the API) relies quite heavily on FML's coremod functions.

I'm also using a bunch of events for various things, and obviously the ore dictionary support in the item tree relies entirely on Forge for that, since that's a Forge function.

**Comment by EasyMFnE** [comment]
Thank you for the very quick response!

When considering a version that would support LiteLoader instead of Forge, I realize that Forge-specific functionality (such as custom blocks/items, custom inventories, etc) would be cut.  At first glance, if those are excluded it may be feasible to use LiteLoader while keeping true to the main purpose.  If I decide to pursue the idea further in the near future, I'll revisit the issues section here with more information.
