### ISSUE TITLE
AE Chest Sorting

### ISSUE THREAD

**Issue by ZeekDaGeek** [Inventory-Tweaks/inventory-tweaks#218]
Forge version: 10.13.2.1236
Mod version: 1.59

When sorting your own inventory with the Applied Energistics Sky Stone chests (either variety) UI open it will cause your inventory to sort to the top left ignoring all rules for inventory sorting you have set.

I'm not too sure if it's because the side of the chest is odd or something but it's a very annoying bug. The chest is a 4 row chest.

**Comment by Kobata** [comment]
Probably an issue with AE's configuration of the chest sections.

**Comment by CarsonF** [comment]
I have the same problem with sky stone chests, TE strongboxes, and TE Satchels. Each do something a little different. But it looks like it's not identifying the rows correctly. 

I just tried with a hardened strongbox. It's more obvious since it's the same size as your inventory that the strongbox and inventory are swapped.

When I hit the "R" key this is the before and after
![before](https://cloud.githubusercontent.com/assets/932566/5256563/1bd7884e-7990-11e4-87df-fdbab23cba66.png)
![after](https://cloud.githubusercontent.com/assets/932566/5256561/1bd09ac0-7990-11e4-82d2-864573640136.png)

When I hit the default sorting button, this is the before and after
![before](https://cloud.githubusercontent.com/assets/932566/5256563/1bd7884e-7990-11e4-87df-fdbab23cba66.png)
![after](https://cloud.githubusercontent.com/assets/932566/5256562/1bd20ae0-7990-11e4-9dbf-8a39f2102f21.png)

@Kobata are you saying this is an implementation issue on AE2's and TE's side?

Forge version: 10.13.2.1231
Mod version: af3bc68
TE: 4.0.0B5-13
AE2: rv1-stable-1

**Comment by Kobata** [comment]
Unless specifically overridden, Inventory Tweaks has to make assumptions about where the player inventory is in the container slot order (because there's nothing that provides that information to us). It defaults to assuming it's in vanilla order [block/special inventory followed by main player inventory], but some modders like to have the opposite order. If they want it to work, they need to provide the function that says where things are in their inventory, or make their inventories match vanilla.

**Comment by CarsonF** [comment]
Thanks for the clarification Kobata.
