### ISSUE TITLE
"No forge"

### ISSUE THREAD

**Issue by Eldraphyn** [Inventory-Tweaks/inventory-tweaks#381]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.61

I have installed forge and everything needed and also put the jar file into the Mods folder in .Minecraft But when I choose the forge profile/Environment it just says "No forge" for the Mod. I dont use the normal launcher, I actually use the Magic launcher because I thought it would be easier etc. It only works for me in the Normal launcher and I also have Optifine installed but for somewhat reason it will not work while I try to use the forge with the Inventory Tweaks Mod.

Forge doesnt work at all for Magic Launcher. Any way to fix it?..

**Comment by Kobata** [comment]
I don't use magic launcher but from what I recall long ago it's very easy to do things incorrectly with it -- you do NOT want to have it editing the minecraft jar directly, ever. Correct operation of Forge requires a launcher capable of using the vanilla 1.6+ launch system, including the 'launchwrapper' which allows it to alter files while loading, instead of the jar.

Since this isn't directly an inventory tweaks issue, I'll close it for now.
