### ISSUE TITLE
Huge explot with inv tweaks + forestry backpacks ~1.4.7

### ISSUE THREAD

**Issue by Pixelmnkey** [Inventory-Tweaks/inventory-tweaks#39]
Hello, first of all such a great mod, realy makes things easier. I was playing using the live version of FTB ultimate, with forestry miner's backpack, and i just noticed that if you press space + click to move all the items from the backpack to your inventory, the items just dupe themself, having the items in your inventory and still in the backpack.

Is this reported yet?

Thanks.

**Comment by Kobata** [comment]
I've already fixed this is 1.5 versions.

There is a large amount of fairly common issues related to mods fixed in the 1.5 versions, so to prevent spam it would help for anyone reporting bugs to verify them on 1.5.1. (There's a forestry beta for 1.5.1 released already so it is possible to check...)

The duping part of this is entirely Forestry's fault though -- Inventory Tweaks does nothing you can't do yourself with the mouse if you were fast enough.

**Comment by Pixelmnkey** [comment]
Would it be posible to fix it in a 1.4.7 version aswell? Most of the servers won't update to 1.5.1 untill rp2 is released :/
