### ISSUE TITLE
DUPLICATION GLITCH 

### ISSUE THREAD

**Issue by Nimmo18** [Inventory-Tweaks/inventory-tweaks#396]
**Minecraft Version:1.10.2**
**Inventory Tweaks Version:1.6.1-68**

Testing around with the mod and it appears in the bottom right hand inventory slot (above the 9 inventory on HUD) if you click on the slot then quickly press r to sort inventory it duplicates the item INFINITELY as many times you want ie i had 64 repeaters and ended up doing the glitch once with 128 this will need fixed 

EDIT: sometimes it will delete that item from your inventory rather than dupe it

**Comment by Kobata** [comment]
See response to #390.

This is most likely caused by some other mod (or a modded server), just exposed by inventory tweaks. 

There have been historically a few times where _creative-mode_ players get unintentional item duplication, but those don't matter because creative-mode lets you duplicate things freely anyway.

**Comment by Nimmo18** [comment]
Ah, yes you are right this is not an issue for Survival
