### ISSUE TITLE
Scroll Moving Not Working

### ISSUE THREAD

**Issue by Zer0t3ch** [Inventory-Tweaks/inventory-tweaks#41]
As of the update for MC 1.5, scrolling to move single items at a time no longer works. Just wondering if that is a bug or if you removed that feature. Thank you!

**Comment by Kobata** [comment]
Someone somewhere reported this before, although I can't find it.

I ended up trying to figure out where detection of that was coming from, and determining that (as far as I can tell) no recent version (MC.1.4.7 or MC1.5) of the mod has checked for scrolling to move items. If it worked before, it would have been because of some strange LWJGL or Minecraft behavior causing it to detect scrolling as a normal click.

**Comment by LepkoQQ** [comment]
Scrolling to move one item at a time is part of NEI.

**Comment by Zer0t3ch** [comment]
Ok, thank you! I didn't realize that. I will be posting somewhere for NEI.
