### ISSUE TITLE
Sorting Problems with Colossal Chests mod

### ISSUE THREAD

**Issue by NovaViper** [Inventory-Tweaks/inventory-tweaks#438]
**Minecraft Version: 1.11.2**
**Inventory Tweaks Version: 1.62-dev 77-7812cce**
**Colossal Chests Version: 1.11.2-1.5.0**
Hey, I notice whenever I try use the shortcut key and middle mouse button to sort items in a Colossal Chest, it doesn't sort the items as stated in the default settings. Yes I can make the items line up vertically and horizontally, but I can't get the items to actually sort. I already reported this issue to the developer and he says that the mod should fully work with Inventory Tweaks and to ask you guys if you have any idea why this isn't working.

**Comment by Kobata** [comment]
From a quick look at that mod, since I'm not very familiar with it, it doesn't appear to be very friendly to the way Inventory Tweaks does sorting -- with the scrollbars there's a big mismatch between what the mod probably knows about (all the items) and what it can actually interact with (what's currently visible).

I don't expect sorting to work well with it at all.

**Comment by NovaViper** [comment]
Ok, I just went and told the developer about it.
