### ISSUE TITLE
Documentation bug / Suggestion: metadata ("damage") format

### ISSUE THREAD

**Issue by tofof** [Inventory-Tweaks/inventory-tweaks#463]
**Minecraft Version:** 1.10.2
**Inventory Tweaks Version:** 1.61-58

Documentation bug 1 - comment at bottom of the InvTweaksRules
---
The comment suggests you can create a rule such as `D9 12345-13` which appears to be a deprecated format. Not working for me at least (tested using red wool's `0035-14` or `35-14` as well as actual mod item `4945-1`).

Documentation bug 2 - first faq item
---
Moved to [appropriate venue](https://github.com/Inventory-Tweaks/Docs/issues/2).

Correct usage
---
Referencing items with metadata only seems to be only possible through invTweaksTree. There, examples like `<redWool id="wool" damage="14"/>` show correct usage for differentiating items by metadata.

Suggestion
---
It'd be nicer if this mod was more in line with current ways of referring to the metadata on an item. Most<sup>[_**1**_](#fallacy1)</sup> mods now refer to red wool as `minecraft:wool:14`, but this format doesn't work in either file.

Searching the documentation for 'metadata' produced no hits. It took ctrl-f'ing the tree file for colored wool - a lucky guess that you'd supported them already - to figure out the syntax. Only then did I discover that I should've searched the documentation for the outdated<sup>[_**2**_](#fallacy1)</sup> term 'damage value'.  At the very least, toss the word 'metadata' in there for better find-ability, please.

Most problematic, however, was that the documentation I did find was incorrect, leading me to try those formats (appending `-14` etc). 

Footnotes 🤓 
---
<a name="fallacy1">1</a>: _argumentum ad populum_ fallacy, but [standardization](https://xkcd.com/927/) is helpful
<a name="fallacy1">2</a>: I have not provided (nor attempted to find) proof that this is no longer the preferred term.

**Comment by Kobata** [comment]
The documentation source is available at [Inventory-Tweaks/Docs](https://github.com/Inventory-Tweaks/Docs)

There's reasons behind various things:
- With the string IDs I can't very reliably tell if one is a reference to the item ID or to a tree key. (It looks like I just straight replaced the old numbers when that change was made and didn't bother looking too much, and I don't think I've ever touched the default rules file)
- The tree file supports more variation than just damage values, so it is helpful to separate them since they're conceptually different anyway (It's worth noting, in particular, than vanilla's `/give` command has them as separate arguments)

**Comment by tofof** [comment]
> The documentation source is available at [Inventory-Tweaks/Docs](https://github.com/Inventory-Tweaks/Docs)

I've moved [doc bug 2 there](https://github.com/Inventory-Tweaks/Docs/issues/2) as a more appropriate venue.

Thanks for the explanation about the format.

**Comment by tofof** [comment]
Bug 1 still belongs in this repo since it's at [line 32 of defaultconfig](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/develop/src/main/resources/assets/inventorytweaks/defaultconfig.dat#L32).
