### ISSUE TITLE
[1.12] Button Overlapping Recipe Book

### ISSUE THREAD

**Issue by SnowShock35** [Inventory-Tweaks/inventory-tweaks#478]
Hello,

I believe I've found a potential issue with Inventory Tweaks for Minecraft 1.12. Here are the details regarding the issue:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2387
- Inventory Tweaks 1.63+dev.94.3cdd29e (What sort of version numbering system is that?!?)

### Issue Details

With Minecraft's addition of it's new recipe book GUI element, Inventory Tweaks has been somewhat _merged_ with it. Also, opening and closing the recipe book causes the button's position to move

### Issue Media

![](https://ss.blamesnow.co.uk/2017/06/1498736673-a3f827f8.png)
![](https://ss.blamesnow.co.uk/2017/06/1498736005-4d52cd84.png)
![](https://ss.blamesnow.co.uk/2017/06/1498736684-969c4246.png)
![](https://ss.blamesnow.co.uk/2017/06/1498736698-7c9030e6.png)

**Comment by Kobata** [comment]
> Alright, I've got a bit of time to actually look at what they did for the recipe book

> WHYYYYY

Ok, seriously, I could probably make it work on the two vanilla UIs that have the button, but nothing else generically.

**Comment by Kobata** [comment]
Ok, so above makes it change the button position when the recipe book opens/closes.

It doesn't do anything about where the button is because your screenshots don't match my testing at *all*
![2017-07-11_03 30 18](https://user-images.githubusercontent.com/2323933/28055978-4b959cea-65e9-11e7-989b-de8bbdd85f36.png)
