### ISSUE TITLE
Hotbar Slots 1-3 jump to Inventory in Iron Furnace on Sort of Inv.

### ISSUE THREAD

**Issue by sojakai** [Inventory-Tweaks/inventory-tweaks#55]
I open the Iron Furnace, move the cursor to my inventory and middleclick to sort. My tools in slots 1-3 of the Hotbar jump into inventory. I have tried putting other items in those slots and they always jump.

Using InventoryTweaks-1.55-dev-b32.jar, but reverted to b28 and the problem is there also. Don't remember seeing this in 1.54, but it was always a problem in Creative Mode.

**Comment by Kobata** [comment]
I'll test tomorrow but I haven't seen any offsets in (plain) creative mode since I do frequently test that.

An offset of 3 is strange though, because the base inventory has 4 extra slots (armor) compared to the view of it in most other containers.

**Comment by Kobata** [comment]
IC2 is adding slots to the end of the container, rather than (as is normal MC convention) the front. While sorting should probably be disabled in unknown containers (I thought it was, but I guess that broke at some point), it would work correctly if they followed the same ordering as all vanilla blocks.

**Comment by Kobata** [comment]
Just for full information, they broke this in IC2-lf-315 (http://ic2api.player.to:8080/job/IC2_lf/315/changes)
