### ISSUE TITLE
Change default sort key to something else.

### ISSUE THREAD

**Issue by IMarvinTPA** [Inventory-Tweaks/inventory-tweaks#570]
**Minecraft Version:** Any
**Inventory Tweaks Version:** Any

JEI's default "Recipe" key is also "R" so your inventory frequently gets resorted when you intended on getting the recipe for the item that was under your cursor.  It is fairly irritating to end up with another recipe or none at all when the items shift.

I tend to move the sort key to the open single quote/tilde key since that is not generally a character in the name of any items.
It may conflict with Ore Excavator/Veinminer since I think that may be the default key for that.  Though I tend to move that key to left alt.

**Comment by Kobata** [comment]
It's been R since, at least, [2011](https://github.com/Inventory-Tweaks/inventory-tweaks/blob/0d5728ee5e3e57777fcc5550fdda071fdbbf2610/src/mod_InvTweaks.java).

I don't see a reason to change it after so long, particularly given that as far as I can find it predates the existence of NEI by a decent time.
