### ISSUE TITLE
InvTweaksTree discussion

### ISSUE THREAD

**Issue by Larandar** [Inventory-Tweaks/inventory-tweaks#60]
Since I'm doing one more time a cleaning in the item tree, I wish to have some help of native english speaker.
Starting in commit https://github.com/Larandar/inventory-tweaks/commit/53c8242f6f071b645b6c2640a126c43c74945da2 I change the way <miningResources> are.
I wan't to now what you think of gem/ingot/dust ( should I use plural ? ) ?
In neer future I will and Thermal Expension, Tinker Construct, IC2 and GregTech support
One last think, is `<gold id="266"/><goldDict oreDictName="ingotGold"/>` necessary ? Or can I write <gold id="266" oreDictName="ingotGold"/> ? The "Dict" suffixe is optional ?
Finally sorry about my poor english, any spell corection is welcome.

**Comment by Kobata** [comment]
Two entries can't have the same name, &lt;gold&gt; matches just the vanilla gold item, &lt;goldDict&gt; matches anything that 'counts' as gold.

I'm not sure if there's currently an ore dictionary entry for gold, although there was one added recently for iron. Those are there for consistency and in case someone adds them later.

I tried to cover the 'common' things in the ore dictionary, but the generic tree file isn't really the best place to put mod items because they don't have fixed IDs. I'm sure some modpack users would like one set up for the IDs their modpack uses, but that is best distributed on those modpack's forums as a separate download.

**Comment by Larandar** [comment]
Of course, I will only add metals/dust with a forge directory. With my config gold has a FD entry.
